###############################################################################
# Copyright (c) 2010-2026 Haifeng Li. All rights reserved.
#
# SMILE is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SMILE is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SMILE. If not, see <https://www.gnu.org/licenses/>.
###############################################################################

[win]defaultFont = +3
[win]MenuBar.font = +2
ProgressBar.arc = 999

# Global monospaced font with fallbacks
monospaced.font = "JetBrains Mono", Monospaced

# Platform specific overrides
[win]monospaced.font = "JetBrains Mono", "Courier New", "Segoe UI Emoji", Monospaced
# On Mac, ligatures will cause uneven spaces sometimes.
[mac]monospaced.font = Menlo, Monaco, "Apple Color Emoji", Monospaced
[linux]monospaced.font = "JetBrains Mono", "Liberation Mono", "Ubuntu Mono", "Noto Color Emoj", Monospaced
