# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  # Keep devcontainer tracking active
 - package-ecosystem: "devcontainers"
   directory: "/"
   schedule:
     interval: weekly

 - package-ecosystem: "gradle"
   directory: "/"
   schedule:
     interval: "weekly"

   # Suppress alerts for build tools and plugins
   ignore:
     - package-name: "org.gradle.*"           # Ignores core Gradle plugins and tooling
     - package-name: "org.jetbrains.kotlin.*" # Ignores Kotlin Gradle/compiler plugins

