// Generated by jextract

package smile.onnx.foreign;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OrtDataTransferImpl {
 *     uint32_t ort_version_supported;
 *     void (*Release)(OrtDataTransferImpl *);
 *     bool (*CanCopy)(const OrtDataTransferImpl *, const OrtMemoryDevice *, const OrtMemoryDevice *);
 *     OrtStatusPtr (*CopyTensors)(OrtDataTransferImpl *, const OrtValue **, OrtValue **, OrtSyncStream **, size_t);
 * }
 * }
 */
public class OrtDataTransferImpl {

    OrtDataTransferImpl() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        onnxruntime_c_api_h.C_INT.withName("ort_version_supported"),
        MemoryLayout.paddingLayout(4),
        onnxruntime_c_api_h.C_POINTER.withName("Release"),
        onnxruntime_c_api_h.C_POINTER.withName("CanCopy"),
        onnxruntime_c_api_h.C_POINTER.withName("CopyTensors")
    ).withName("OrtDataTransferImpl");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt ort_version_supported$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ort_version_supported"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static final OfInt ort_version_supported$layout() {
        return ort_version_supported$LAYOUT;
    }

    private static final long ort_version_supported$OFFSET = $LAYOUT.byteOffset(groupElement("ort_version_supported"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static final long ort_version_supported$offset() {
        return ort_version_supported$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static int ort_version_supported(MemorySegment struct) {
        return struct.get(ort_version_supported$LAYOUT, ort_version_supported$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static void ort_version_supported(MemorySegment struct, int fieldValue) {
        struct.set(ort_version_supported$LAYOUT, ort_version_supported$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*Release)(OrtDataTransferImpl *)
     * }
     */
    public final static class Release {

        private Release() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(Release.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Release.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout Release$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Release"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*Release)(OrtDataTransferImpl *)
     * }
     */
    public static final AddressLayout Release$layout() {
        return Release$LAYOUT;
    }

    private static final long Release$OFFSET = $LAYOUT.byteOffset(groupElement("Release"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*Release)(OrtDataTransferImpl *)
     * }
     */
    public static final long Release$offset() {
        return Release$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*Release)(OrtDataTransferImpl *)
     * }
     */
    public static MemorySegment Release(MemorySegment struct) {
        return struct.get(Release$LAYOUT, Release$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*Release)(OrtDataTransferImpl *)
     * }
     */
    public static void Release(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Release$LAYOUT, Release$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*CanCopy)(const OrtDataTransferImpl *, const OrtMemoryDevice *, const OrtMemoryDevice *)
     * }
     */
    public final static class CanCopy {

        private CanCopy() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_BOOL,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(CanCopy.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(CanCopy.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout CanCopy$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("CanCopy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*CanCopy)(const OrtDataTransferImpl *, const OrtMemoryDevice *, const OrtMemoryDevice *)
     * }
     */
    public static final AddressLayout CanCopy$layout() {
        return CanCopy$LAYOUT;
    }

    private static final long CanCopy$OFFSET = $LAYOUT.byteOffset(groupElement("CanCopy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*CanCopy)(const OrtDataTransferImpl *, const OrtMemoryDevice *, const OrtMemoryDevice *)
     * }
     */
    public static final long CanCopy$offset() {
        return CanCopy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*CanCopy)(const OrtDataTransferImpl *, const OrtMemoryDevice *, const OrtMemoryDevice *)
     * }
     */
    public static MemorySegment CanCopy(MemorySegment struct) {
        return struct.get(CanCopy$LAYOUT, CanCopy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*CanCopy)(const OrtDataTransferImpl *, const OrtMemoryDevice *, const OrtMemoryDevice *)
     * }
     */
    public static void CanCopy(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(CanCopy$LAYOUT, CanCopy$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*CopyTensors)(OrtDataTransferImpl *, const OrtValue **, OrtValue **, OrtSyncStream **, size_t)
     * }
     */
    public final static class CopyTensors {

        private CopyTensors() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, long _x4);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(CopyTensors.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(CopyTensors.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, long _x4) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout CopyTensors$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("CopyTensors"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CopyTensors)(OrtDataTransferImpl *, const OrtValue **, OrtValue **, OrtSyncStream **, size_t)
     * }
     */
    public static final AddressLayout CopyTensors$layout() {
        return CopyTensors$LAYOUT;
    }

    private static final long CopyTensors$OFFSET = $LAYOUT.byteOffset(groupElement("CopyTensors"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CopyTensors)(OrtDataTransferImpl *, const OrtValue **, OrtValue **, OrtSyncStream **, size_t)
     * }
     */
    public static final long CopyTensors$offset() {
        return CopyTensors$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CopyTensors)(OrtDataTransferImpl *, const OrtValue **, OrtValue **, OrtSyncStream **, size_t)
     * }
     */
    public static MemorySegment CopyTensors(MemorySegment struct) {
        return struct.get(CopyTensors$LAYOUT, CopyTensors$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CopyTensors)(OrtDataTransferImpl *, const OrtValue **, OrtValue **, OrtSyncStream **, size_t)
     * }
     */
    public static void CopyTensors(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(CopyTensors$LAYOUT, CopyTensors$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

