/*
 * Copyright (c) 2010-2026 Haifeng Li. All rights reserved.
 *
 * SMILE is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SMILE is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SMILE. If not, see <https://www.gnu.org/licenses/>.
 */
package smile.deep.tensor;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.lang.invoke.MethodHandle;
import java.lang.ref.Cleaner;
import smile.torch.smile_torch_h;

/**
 * Internal helpers for the FFM (Foreign Function and Memory API) binding to the
 * {@code smile_torch} native library. This class glues the idiomatic
 * {@code smile.deep.tensor} API to the raw {@link smile.torch.smile_torch_h}
 * downcall stubs generated by jextract.
 *
 * <p>It centralizes three concerns: converting native error sentinels into Java
 * exceptions, freeing native handles when their Java wrappers become
 * unreachable (via a shared {@link Cleaner}), and a handful of downcalls for
 * functions that are not yet covered by the generated bindings.
 *
 * @author Haifeng Li
 */
final class Native {
    private Native() {
    }

    /**
     * Shared cleaner that releases native handles owned by Java wrappers
     * (tensors, indices, …) once those wrappers are no longer reachable. It is a
     * safety net; callers should still close resources deterministically via
     * try-with-resources or an {@link smile.util.AutoScope} where possible.
     */
    static final Cleaner CLEANER = Cleaner.create();

    /**
     * Returns the message describing the most recent native failure, or an empty
     * string if none.
     * @return the last native error message.
     */
    static String lastError() {
        MemorySegment s = smile_torch_h.smile_last_error();
        if (s == null || s.address() == 0) return "";
        return s.reinterpret(Long.MAX_VALUE).getString(0);
    }

    /**
     * Verifies that a native call returned a non-null handle, throwing the
     * native error message otherwise.
     * @param handle the handle returned by a native call.
     * @return the validated handle.
     */
    static MemorySegment check(MemorySegment handle) {
        if (handle == null || handle.address() == 0) {
            String msg = lastError();
            throw new RuntimeException(msg.isEmpty() ? "smile_torch native call failed" : msg);
        }
        return handle;
    }

    /** Frees an {@code ST_Tensor} handle exactly once. Used as a cleaning action. */
    record FreeTensor(MemorySegment handle) implements Runnable {
        @Override public void run() {
            smile_torch_h.smile_tensor_free(handle);
        }
    }

    /** Frees an {@code ST_TensorIndex} handle exactly once. Used as a cleaning action. */
    record FreeIndex(MemorySegment handle) implements Runnable {
        @Override public void run() {
            smile_torch_h.smile_tensor_index_free(handle);
        }
    }

    // =========================================================================
    // Downcalls for functions not yet covered by the generated bindings.
    //
    // These resolve their native symbols lazily (on first use) so that the
    // tensor package loads even against an older smile_torch binary; only the
    // specific methods below require a rebuilt library. The corresponding C
    // declarations live in deep/src/main/cpp/smile_torch.{h,cpp}.
    // =========================================================================

    private static final Linker LINKER = Linker.nativeLinker();
    private static final SymbolLookup LOOKUP =
            SymbolLookup.libraryLookup(System.mapLibraryName("smile_torch"), Arena.ofAuto())
                    .or(LINKER.defaultLookup());

    private static MethodHandle downcall(String name, FunctionDescriptor descriptor) {
        return LINKER.downcallHandle(LOOKUP.findOrThrow(name), descriptor);
    }

    /** {@code ST_Device smile_tensor_device(ST_Tensor t)} */
    private static final class TensorDevice {
        static final MethodHandle HANDLE = downcall("smile_tensor_device",
                FunctionDescriptor.of(smile_torch_h.C_POINTER, smile_torch_h.C_POINTER));
    }

    /** {@code ST_TensorIndex smile_tensor_index_none(void)} */
    private static final class IndexNone {
        static final MethodHandle HANDLE = downcall("smile_tensor_index_none",
                FunctionDescriptor.of(smile_torch_h.C_POINTER));
    }

    /** {@code ST_Tensor smile_tensor_scatter_reduce(ST_Tensor, int64_t, ST_Tensor, ST_Tensor, const char*)} */
    private static final class ScatterReduce {
        static final MethodHandle HANDLE = downcall("smile_tensor_scatter_reduce",
                FunctionDescriptor.of(smile_torch_h.C_POINTER,
                        smile_torch_h.C_POINTER, smile_torch_h.C_LONG,
                        smile_torch_h.C_POINTER, smile_torch_h.C_POINTER, smile_torch_h.C_POINTER));
    }

    /** {@code void smile_tensor_scatter_reduce_(ST_Tensor, int64_t, ST_Tensor, ST_Tensor, const char*)} */
    private static final class ScatterReduceInplace {
        static final MethodHandle HANDLE = downcall("smile_tensor_scatter_reduce_",
                FunctionDescriptor.ofVoid(smile_torch_h.C_POINTER, smile_torch_h.C_LONG,
                        smile_torch_h.C_POINTER, smile_torch_h.C_POINTER, smile_torch_h.C_POINTER));
    }

    /**
     * Returns the compute device of a tensor as a new {@code ST_Device} handle
     * that the caller must free.
     * @param tensor the {@code ST_Tensor} handle.
     * @return a new {@code ST_Device} handle.
     */
    static MemorySegment tensorDevice(MemorySegment tensor) {
        try {
            return (MemorySegment) TensorDevice.HANDLE.invokeExact(tensor);
        } catch (Throwable ex) {
            throw new AssertionError("should not reach here", ex);
        }
    }

    /**
     * Creates a {@code None} ({@code newaxis}) tensor index.
     * @return a new {@code ST_TensorIndex} handle.
     */
    static MemorySegment indexNone() {
        try {
            return (MemorySegment) IndexNone.HANDLE.invokeExact();
        } catch (Throwable ex) {
            throw new AssertionError("should not reach here", ex);
        }
    }

    /**
     * Out-of-place {@code scatter_reduce}.
     * @param tensor the {@code ST_Tensor} handle.
     * @param dim the axis along which to index.
     * @param index the {@code ST_Tensor} handle of indices.
     * @param source the {@code ST_Tensor} handle of source values.
     * @param reduce the {@code const char*} reduction name.
     * @return a new {@code ST_Tensor} handle.
     */
    static MemorySegment scatterReduce(MemorySegment tensor, long dim, MemorySegment index,
                                       MemorySegment source, MemorySegment reduce) {
        try {
            return (MemorySegment) ScatterReduce.HANDLE.invokeExact(tensor, dim, index, source, reduce);
        } catch (Throwable ex) {
            throw new AssertionError("should not reach here", ex);
        }
    }

    /**
     * In-place {@code scatter_reduce}.
     * @param tensor the {@code ST_Tensor} handle.
     * @param dim the axis along which to index.
     * @param index the {@code ST_Tensor} handle of indices.
     * @param source the {@code ST_Tensor} handle of source values.
     * @param reduce the {@code const char*} reduction name.
     */
    static void scatterReduceInplace(MemorySegment tensor, long dim, MemorySegment index,
                                     MemorySegment source, MemorySegment reduce) {
        try {
            ScatterReduceInplace.HANDLE.invokeExact(tensor, dim, index, source, reduce);
        } catch (Throwable ex) {
            throw new AssertionError("should not reach here", ex);
        }
    }
}
