/*
 * Copyright (c) 2010-2026 Haifeng Li. All rights reserved.
 *
 * SMILE is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SMILE is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SMILE. If not, see <https://www.gnu.org/licenses/>.
 */
package smile.deep.tensor;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.lang.invoke.MethodHandle;
import java.lang.ref.Cleaner;
import smile.torch.smile_torch_h;

/**
 * Internal helpers for the FFM (Foreign Function and Memory API) binding to the
 * {@code smile_torch} native library. This class glues the idiomatic
 * {@code smile.deep.tensor} API to the raw {@link smile.torch.smile_torch_h}
 * downcall stubs generated by jextract.
 *
 * <p>It centralizes three concerns: converting native error sentinels into Java
 * exceptions, freeing native handles when their Java wrappers become
 * unreachable (via a shared {@link Cleaner}), and a handful of downcalls for
 * functions that are not yet covered by the generated bindings.
 *
 * @author Haifeng Li
 */
public final class Native {
    private Native() {
    }

    /**
     * Shared cleaner that releases native handles owned by Java wrappers
     * (tensors, indices, modules, …) once those wrappers are no longer
     * reachable. It is a safety net; callers should still close resources
     * deterministically via try-with-resources or an
     * {@link smile.util.AutoScope} where possible.
     */
    public static final Cleaner CLEANER = Cleaner.create();

    /**
     * Returns the message describing the most recent native failure, or an empty
     * string if none.
     * @return the last native error message.
     */
    public static String lastError() {
        MemorySegment s = smile_torch_h.smile_last_error();
        if (s == null || s.address() == 0) return "";
        return s.reinterpret(Long.MAX_VALUE).getString(0);
    }

    /**
     * Verifies that a native call returned a non-null handle, throwing the
     * native error message otherwise.
     * @param handle the handle returned by a native call.
     * @return the validated handle.
     */
    public static MemorySegment check(MemorySegment handle) {
        if (handle == null || handle.address() == 0) {
            String msg = lastError();
            throw new RuntimeException(msg.isEmpty() ? "smile_torch native call failed" : msg);
        }
        return handle;
    }

    /** Frees an {@code ST_Tensor} handle exactly once. Used as a cleaning action. */
    record FreeTensor(MemorySegment handle) implements Runnable {
        @Override public void run() {
            smile_torch_h.smile_tensor_free(handle);
        }
    }

    /** Frees an {@code ST_TensorIndex} handle exactly once. Used as a cleaning action. */
    record FreeIndex(MemorySegment handle) implements Runnable {
        @Override public void run() {
            smile_torch_h.smile_tensor_index_free(handle);
        }
    }
}
