/*
 * Copyright (c) 2010-2026 Haifeng Li. All rights reserved.
 *
 * SMILE is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SMILE is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SMILE. If not, see <https://www.gnu.org/licenses/>.
 */
package smile.torch;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.MethodHandle;
import java.lang.ref.Cleaner;
import java.util.Map;
import smile.deep.tensor.Tensor;

/**
 * Internal helpers for the FFM (Foreign Function and Memory API) binding to the
 * {@code smile_torch} native library. This class glues the idiomatic
 * {@code smile.deep.tensor} API to the raw {@link smile.torch.smile_torch_h}
 * downcall stubs generated by jextract.
 *
 * <p>It centralizes three concerns: converting native error sentinels into Java
 * exceptions, freeing native handles when their Java wrappers become
 * unreachable (via a shared {@link Cleaner}), and a handful of downcalls for
 * functions that are not yet covered by the generated bindings.
 *
 * @author Haifeng Li
 */
public final class Native {
    private Native() {
    }

    /**
     * Shared cleaner that releases native handles owned by Java wrappers
     * (tensors, indices, modules, …) once those wrappers are no longer
     * reachable. It is a safety net; callers should still close resources
     * deterministically via try-with-resources or an
     * {@link smile.util.AutoScope} where possible.
     */
    public static final Cleaner CLEANER = Cleaner.create();

    private static final class Bindings {
        static final Linker LINKER = Linker.nativeLinker();
        static final MethodHandle LOAD_STATE_DICT = LINKER.downcallHandle(
                smile_torch_h.SYMBOL_LOOKUP.findOrThrow("smile_module_load_state_dict"),
                FunctionDescriptor.of(ValueLayout.JAVA_INT,
                        ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
                        ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));
        static final MethodHandle TENSOR_COPY = LINKER.downcallHandle(
                smile_torch_h.SYMBOL_LOOKUP.findOrThrow("smile_tensor_copy_"),
                FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.ADDRESS));
        static final MethodHandle CUDA_MEM_GET_INFO = LINKER.downcallHandle(
                smile_torch_h.SYMBOL_LOOKUP.findOrThrow("smile_cuda_mem_get_info"),
                FunctionDescriptor.of(ValueLayout.JAVA_INT,
                        ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
        static final MethodHandle CUDA_ALLOCATOR_STATS = LINKER.downcallHandle(
                smile_torch_h.SYMBOL_LOOKUP.findOrThrow("smile_cuda_allocator_stats"),
                FunctionDescriptor.of(ValueLayout.JAVA_INT,
                        ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
        static final java.util.Optional<MemorySegment> CUDA_COMPUTE_CAPABILITY_SYM =
                smile_torch_h.SYMBOL_LOOKUP.find("smile_cuda_compute_capability");
        static final MethodHandle CUDA_COMPUTE_CAPABILITY = CUDA_COMPUTE_CAPABILITY_SYM
                .map(s -> LINKER.downcallHandle(s, FunctionDescriptor.of(ValueLayout.JAVA_INT,
                        ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS)))
                .orElse(null);
        static final java.util.Optional<MemorySegment> SCALED_MM_SYM =
                smile_torch_h.SYMBOL_LOOKUP.find("smile_scaled_mm");
        static final MethodHandle SCALED_MM = SCALED_MM_SYM
                .map(s -> LINKER.downcallHandle(s, FunctionDescriptor.of(ValueLayout.ADDRESS,
                        ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
                        ValueLayout.ADDRESS, ValueLayout.JAVA_INT)))
                .orElse(null);
        static final java.util.Optional<MemorySegment> SCALED_MM_V2_SYM =
                smile_torch_h.SYMBOL_LOOKUP.find("smile_scaled_mm_v2");
        static final MethodHandle SCALED_MM_V2 = SCALED_MM_V2_SYM
                .map(s -> LINKER.downcallHandle(s, FunctionDescriptor.of(ValueLayout.ADDRESS,
                        ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
                        ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT,
                        ValueLayout.JAVA_INT)))
                .orElse(null);
        static final java.util.Optional<MemorySegment> FP8_QUANT_1X128_SYM =
                smile_torch_h.SYMBOL_LOOKUP.find("smile_fp8_quant_1x128");
        static final MethodHandle FP8_QUANT_1X128 = FP8_QUANT_1X128_SYM
                .map(s -> LINKER.downcallHandle(s, FunctionDescriptor.of(ValueLayout.ADDRESS,
                        ValueLayout.ADDRESS, ValueLayout.ADDRESS)))
                .orElse(null);
        static final java.util.Optional<MemorySegment> MARLIN_MUL_SYM =
                smile_torch_h.SYMBOL_LOOKUP.find("smile_marlin_mul");
        static final MethodHandle MARLIN_MUL = MARLIN_MUL_SYM
                .map(s -> LINKER.downcallHandle(s, FunctionDescriptor.of(ValueLayout.ADDRESS,
                        ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
                        ValueLayout.ADDRESS, ValueLayout.JAVA_INT)))
                .orElse(null);
        static final java.util.Optional<MemorySegment> MARLIN_AVAILABLE_SYM =
                smile_torch_h.SYMBOL_LOOKUP.find("smile_marlin_available");
        static final MethodHandle MARLIN_AVAILABLE = MARLIN_AVAILABLE_SYM
                .map(s -> LINKER.downcallHandle(s, FunctionDescriptor.of(ValueLayout.JAVA_INT)))
                .orElse(null);
        static final MethodHandle MODULE_SET_REQUIRES_GRAD = LINKER.downcallHandle(
                smile_torch_h.SYMBOL_LOOKUP.findOrThrow("smile_module_set_requires_grad"),
                FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        static final java.util.Optional<MemorySegment> MODULE_UNREGISTER_SYM =
                smile_torch_h.SYMBOL_LOOKUP.find("smile_module_unregister_module");
        static final MethodHandle MODULE_UNREGISTER = MODULE_UNREGISTER_SYM
                .map(s -> LINKER.downcallHandle(s, FunctionDescriptor.ofVoid(
                        ValueLayout.ADDRESS, ValueLayout.ADDRESS)))
                .orElse(null);
        static final MethodHandle TENSOR_NBYTES = LINKER.downcallHandle(
                smile_torch_h.SYMBOL_LOOKUP.findOrThrow("smile_tensor_nbytes"),
                FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
        static final MethodHandle TENSOR_DATA_PTR = LINKER.downcallHandle(
                smile_torch_h.SYMBOL_LOOKUP.findOrThrow("smile_tensor_data_ptr"),
                FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));
        static final MethodHandle TP_ALL_REDUCE_SUM = LINKER.downcallHandle(
                smile_torch_h.SYMBOL_LOOKUP.findOrThrow("smile_tp_all_reduce_sum"),
                FunctionDescriptor.of(ValueLayout.JAVA_INT,
                        ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        static final MethodHandle TP_BROADCAST = LINKER.downcallHandle(
                smile_torch_h.SYMBOL_LOOKUP.findOrThrow("smile_tp_broadcast"),
                FunctionDescriptor.of(ValueLayout.JAVA_INT,
                        ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
        static final MethodHandle NCCL_COMM_CREATE = LINKER.downcallHandle(
                smile_torch_h.SYMBOL_LOOKUP.findOrThrow("smile_nccl_comm_create"),
                FunctionDescriptor.of(ValueLayout.ADDRESS,
                        ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
        static final MethodHandle NCCL_COMM_FREE = LINKER.downcallHandle(
                smile_torch_h.SYMBOL_LOOKUP.findOrThrow("smile_nccl_comm_free"),
                FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
        static final MethodHandle NCCL_ALL_REDUCE_SUM = LINKER.downcallHandle(
                smile_torch_h.SYMBOL_LOOKUP.findOrThrow("smile_nccl_all_reduce_sum"),
                FunctionDescriptor.of(ValueLayout.JAVA_INT,
                        ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
        static final MethodHandle NCCL_BROADCAST = LINKER.downcallHandle(
                smile_torch_h.SYMBOL_LOOKUP.findOrThrow("smile_nccl_broadcast"),
                FunctionDescriptor.of(ValueLayout.JAVA_INT,
                        ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT,
                        ValueLayout.ADDRESS));
        static final MethodHandle RECURRENT_GATED_DELTA = LINKER.downcallHandle(
                smile_torch_h.SYMBOL_LOOKUP.findOrThrow("smile_recurrent_gated_delta_rule"),
                FunctionDescriptor.of(ValueLayout.ADDRESS,
                        ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
                        ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
                        ValueLayout.JAVA_INT));
        static final java.util.Optional<MemorySegment> FLASHINFER_AVAILABLE_SYM =
                smile_torch_h.SYMBOL_LOOKUP.find("smile_flashinfer_is_available");
        static final MethodHandle FLASHINFER_AVAILABLE = FLASHINFER_AVAILABLE_SYM
                .map(s -> LINKER.downcallHandle(s, FunctionDescriptor.of(ValueLayout.JAVA_INT)))
                .orElse(null);
        static final MethodHandle FLASHINFER_WS_CREATE = smile_torch_h.SYMBOL_LOOKUP
                .find("smile_flashinfer_workspace_create")
                .map(s -> LINKER.downcallHandle(s, FunctionDescriptor.of(ValueLayout.ADDRESS,
                        ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG)))
                .orElse(null);
        static final MethodHandle FLASHINFER_WS_FREE = smile_torch_h.SYMBOL_LOOKUP
                .find("smile_flashinfer_workspace_free")
                .map(s -> LINKER.downcallHandle(s, FunctionDescriptor.ofVoid(ValueLayout.ADDRESS)))
                .orElse(null);
        static final MethodHandle FLASHINFER_SET_AOT = smile_torch_h.SYMBOL_LOOKUP
                .find("smile_flashinfer_set_aot_dir")
                .map(s -> LINKER.downcallHandle(s, FunctionDescriptor.ofVoid(ValueLayout.ADDRESS)))
                .orElse(null);
        static final MethodHandle FLASHINFER_PAGED = smile_torch_h.SYMBOL_LOOKUP
                .find("smile_flashinfer_paged_attention")
                .map(s -> LINKER.downcallHandle(s, FunctionDescriptor.of(ValueLayout.ADDRESS,
                        ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
                        ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
                        ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT,
                        ValueLayout.JAVA_INT, ValueLayout.JAVA_DOUBLE,
                        ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT,
                        ValueLayout.JAVA_INT,
                        ValueLayout.ADDRESS, ValueLayout.ADDRESS)))
                .orElse(null);
        static final MethodHandle FLASHINFER_RAGGED = smile_torch_h.SYMBOL_LOOKUP
                .find("smile_flashinfer_ragged_attention")
                .map(s -> LINKER.downcallHandle(s, FunctionDescriptor.of(ValueLayout.ADDRESS,
                        ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
                        ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT,
                        ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_INT, ValueLayout.ADDRESS)))
                .orElse(null);
    }

    /**
     * Returns the message describing the most recent native failure, or an empty
     * string if none.
     * @return the last native error message.
     */
    public static String lastError() {
        MemorySegment s = smile_torch_h.smile_last_error();
        if (s == null || s.address() == 0) return "";
        return s.reinterpret(Long.MAX_VALUE).getString(0);
    }

    /**
     * Verifies that a native call returned a non-null handle, throwing the
     * native error message otherwise.
     * @param handle the handle returned by a native call.
     * @return the validated handle.
     */
    public static MemorySegment check(MemorySegment handle) {
        if (handle == null || handle.address() == 0) {
            String msg = lastError();
            throw new RuntimeException(msg.isEmpty() ? "smile_torch native call failed" : msg);
        }
        return handle;
    }

    /**
     * Copies {@code src} into {@code dst} in-place.
     *
     * @param dst the destination tensor.
     * @param src the source tensor.
     */
    public static void copy_(Tensor dst, Tensor src) {
        try {
            Bindings.TENSOR_COPY.invokeExact(dst.handle(), src.handle());
        } catch (Throwable t) {
            throw new RuntimeException(lastError().isEmpty() ? t.getMessage() : lastError(), t);
        }
        String err = lastError();
        if (!err.isEmpty()) {
            throw new RuntimeException(err);
        }
    }

    /**
     * Loads a flat state dict into a module by matching {@code named_parameters()} keys.
     *
     * @param module the native {@code ST_Module} handle.
     * @param stateDict map from fully-qualified parameter name to tensor.
     * @param strict when {@code true}, every module parameter must be present and
     *               every state-dict key must match a module parameter.
     */
    public static void loadStateDict(MemorySegment module, Map<String, Tensor> stateDict, boolean strict) {
        if (stateDict.isEmpty()) {
            if (strict) {
                throw new IllegalArgumentException("Empty state dict with strict=true");
            }
            return;
        }

        try (Arena arena = Arena.ofConfined()) {
            int n = stateDict.size();
            MemorySegment names = arena.allocate(ValueLayout.ADDRESS, n);
            MemorySegment tensors = arena.allocate(ValueLayout.ADDRESS, n);
            int i = 0;
            for (var entry : stateDict.entrySet()) {
                names.setAtIndex(ValueLayout.ADDRESS, i, arena.allocateFrom(entry.getKey()));
                tensors.setAtIndex(ValueLayout.ADDRESS, i, entry.getValue().handle());
                i++;
            }

            int rc;
            try {
                rc = (int) Bindings.LOAD_STATE_DICT.invokeExact(
                        module, names, tensors, (long) n, strict ? 1 : 0);
            } catch (Throwable t) {
                throw new RuntimeException("smile_module_load_state_dict failed", t);
            }
            if (rc != 0) {
                String msg = lastError();
                throw new RuntimeException(msg.isEmpty()
                        ? "smile_module_load_state_dict failed" : msg);
            }
        }
    }

    /**
     * Queries free and total CUDA device memory via LibTorch's caching allocator
     * ({@code cudaMemGetInfo} under a device guard).
     *
     * <p>Requires a {@code smile_torch} binary built with {@code USE_CUDA}
     * (CUDA Toolkit + CUDA LibTorch). A CPU-only build fails with a clear
     * native error rather than a silent {@code -1}.
     *
     * @param deviceIndex the CUDA device index.
     * @return {@code long[2]} of {@code {freeBytes, totalBytes}}.
     * @throws RuntimeException if the query fails (e.g. CUDA unavailable).
     */
    public static long[] cudaMemGetInfo(int deviceIndex) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment free = arena.allocate(ValueLayout.JAVA_LONG);
            MemorySegment total = arena.allocate(ValueLayout.JAVA_LONG);
            int rc;
            try {
                rc = (int) Bindings.CUDA_MEM_GET_INFO.invokeExact(deviceIndex, free, total);
            } catch (Throwable t) {
                throw new RuntimeException("smile_cuda_mem_get_info failed", t);
            }
            if (rc != 0) {
                String msg = lastError();
                throw new RuntimeException(msg.isEmpty()
                        ? "smile_cuda_mem_get_info failed" : msg);
            }
            return new long[]{free.get(ValueLayout.JAVA_LONG, 0), total.get(ValueLayout.JAVA_LONG, 0)};
        }
    }

    /**
     * Queries CUDACachingAllocator live vs reserved bytes for a device.
     *
     * <p>{@code allocated} is storage owned by live tensors; {@code reserved} is
     * the cudaMalloc footprint (includes free cached blocks that
     * {@link smile.deep.tensor.Device#emptyCache()} can return to the driver).
     *
     * @param deviceIndex the CUDA device index.
     * @return {@code long[2]} of {@code {allocatedBytes, reservedBytes}}.
     * @throws RuntimeException if the query fails.
     */
    public static long[] cudaAllocatorStats(int deviceIndex) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment allocated = arena.allocate(ValueLayout.JAVA_LONG);
            MemorySegment reserved = arena.allocate(ValueLayout.JAVA_LONG);
            int rc;
            try {
                rc = (int) Bindings.CUDA_ALLOCATOR_STATS.invokeExact(
                        deviceIndex, allocated, reserved);
            } catch (Throwable t) {
                throw new RuntimeException("smile_cuda_allocator_stats failed", t);
            }
            if (rc != 0) {
                String msg = lastError();
                throw new RuntimeException(msg.isEmpty()
                        ? "smile_cuda_allocator_stats failed" : msg);
            }
            return new long[]{
                    allocated.get(ValueLayout.JAVA_LONG, 0),
                    reserved.get(ValueLayout.JAVA_LONG, 0)};
        }
    }

    /**
     * Returns CUDA compute capability {@code {major, minor}} for a device.
     *
     * @param deviceIndex CUDA device index.
     * @return {@code int[2]} of {@code {major, minor}}.
     * @throws RuntimeException if the query fails or the symbol is missing
     *                          (rebuild {@code libsmile_torch} with CUDA).
     */
    public static int[] cudaComputeCapability(int deviceIndex) {
        if (Bindings.CUDA_COMPUTE_CAPABILITY == null) {
            throw new RuntimeException(
                    "smile_cuda_compute_capability unavailable; rebuild libsmile_torch");
        }
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment major = arena.allocate(ValueLayout.JAVA_INT);
            MemorySegment minor = arena.allocate(ValueLayout.JAVA_INT);
            int rc;
            try {
                rc = (int) Bindings.CUDA_COMPUTE_CAPABILITY.invokeExact(
                        deviceIndex, major, minor);
            } catch (Throwable t) {
                throw new RuntimeException("smile_cuda_compute_capability failed", t);
            }
            if (rc != 0) {
                String msg = lastError();
                throw new RuntimeException(msg.isEmpty()
                        ? "smile_cuda_compute_capability failed" : msg);
            }
            return new int[]{
                    major.get(ValueLayout.JAVA_INT, 0),
                    minor.get(ValueLayout.JAVA_INT, 0)};
        }
    }

    /**
     * Scaled FP8 matrix multiply via LibTorch {@code at::_scaled_mm} (cuBLASLt).
     *
     * @param a        FP8 activation {@code [M,K]}.
     * @param b        FP8 weight layout expected by {@code _scaled_mm} {@code [N,K]}.
     * @param scaleA   float scale for {@code a}.
     * @param scaleB   float scale for {@code b}.
     * @param outDtype output {@link smile.deep.tensor.ScalarType} code
     *                 ({@link smile.torch.smile_torch_h#ST_DTYPE_BFloat16()} etc.).
     * @return output tensor, or {@code null} if the native path is unavailable.
     */
    public static Tensor scaledMm(Tensor a, Tensor b, Tensor scaleA, Tensor scaleB, int outDtype) {
        if (Bindings.SCALED_MM == null) {
            return null;
        }
        MemorySegment out;
        try {
            out = (MemorySegment) Bindings.SCALED_MM.invokeExact(
                    a.handle(), b.handle(), scaleA.handle(), scaleB.handle(), outDtype);
        } catch (Throwable t) {
            String err = lastError();
            if (err != null && !err.isEmpty()) {
                throw new RuntimeException(err, t);
            }
            return null;
        }
        if (out == null || out.address() == 0) {
            String err = lastError();
            if (err != null && !err.isEmpty()) {
                throw new RuntimeException(err);
            }
            return null;
        }
        return new Tensor(out);
    }

    /**
     * {@code at::blas::ScalingType} ordinals for {@link #scaledMmV2}.
     */
    public static final int SCALING_TENSOR_WISE = 0;
    public static final int SCALING_ROW_WISE = 1;
    public static final int SCALING_BLOCK_WISE_1X128 = 4;
    public static final int SCALING_BLOCK_WISE_128X128 = 5;

    /**
     * Block-scaled FP8 matrix multiply via LibTorch {@code at::_scaled_mm_v2}.
     *
     * @param a        FP8 activation {@code [M,K]}.
     * @param b        FP8 weight {@code [N,K]}.
     * @param scaleA   float32 scales for {@code a} (BlockWise1x128 layout).
     * @param scaleB   float32 scales for {@code b} (BlockWise128x128 layout).
     * @param recipeA  {@code ScalingType} ordinal for {@code a}.
     * @param recipeB  {@code ScalingType} ordinal for {@code b}.
     * @param outDtype output dtype code.
     * @return output tensor, or {@code null} if unavailable.
     */
    public static Tensor scaledMmV2(Tensor a, Tensor b, Tensor scaleA, Tensor scaleB,
                                    int recipeA, int recipeB, int outDtype) {
        if (Bindings.SCALED_MM_V2 == null) {
            return null;
        }
        MemorySegment out;
        try {
            out = (MemorySegment) Bindings.SCALED_MM_V2.invokeExact(
                    a.handle(), b.handle(), scaleA.handle(), scaleB.handle(),
                    recipeA, recipeB, outDtype);
        } catch (Throwable t) {
            String err = lastError();
            if (err != null && !err.isEmpty()) {
                throw new RuntimeException(err, t);
            }
            return null;
        }
        if (out == null || out.address() == 0) {
            String err = lastError();
            if (err != null && !err.isEmpty()) {
                throw new RuntimeException(err);
            }
            return null;
        }
        return new Tensor(out);
    }

    /** @return {@code true} when {@link #scaledMmV2} is compiled into {@code libsmile_torch}. */
    public static boolean scaledMmV2Available() {
        return Bindings.SCALED_MM_V2 != null;
    }

    /**
     * Dynamic BlockWise1x128 activation quantize on CUDA.
     *
     * @param input {@code [M,K]} with {@code K % 128 == 0}.
     * @return {@code {fp8 [M,K], scale [M, K/128]}} or {@code null} if unavailable.
     */
    public static Tensor[] fp8Quant1x128(Tensor input) {
        if (Bindings.FP8_QUANT_1X128 == null) {
            return null;
        }
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment scaleOut = arena.allocate(ValueLayout.ADDRESS);
            MemorySegment fp8;
            try {
                fp8 = (MemorySegment) Bindings.FP8_QUANT_1X128.invokeExact(
                        input.handle(), scaleOut);
            } catch (Throwable t) {
                String err = lastError();
                if (err != null && !err.isEmpty()) {
                    throw new RuntimeException(err, t);
                }
                return null;
            }
            if (fp8 == null || fp8.address() == 0) {
                String err = lastError();
                if (err != null && !err.isEmpty()) {
                    throw new RuntimeException(err);
                }
                return null;
            }
            MemorySegment scaleHandle = scaleOut.get(ValueLayout.ADDRESS, 0);
            if (scaleHandle == null || scaleHandle.address() == 0) {
                Tensor fp8Tensor = new Tensor(fp8);
                fp8Tensor.close();
                throw new RuntimeException("smile_fp8_quant_1x128: missing scale output");
            }
            return new Tensor[] { new Tensor(fp8), new Tensor(scaleHandle) };
        }
    }

    /** @return {@code true} when {@link #fp8Quant1x128} is compiled into {@code libsmile_torch}. */
    public static boolean fp8Quant1x128Available() {
        return Bindings.FP8_QUANT_1X128 != null;
    }

    /** @return {@code true} when Marlin is compiled into {@code libsmile_torch}. */
    public static boolean marlinAvailable() {
        if (Bindings.MARLIN_AVAILABLE == null) {
            return false;
        }
        try {
            return ((int) Bindings.MARLIN_AVAILABLE.invokeExact()) != 0;
        } catch (Throwable t) {
            return false;
        }
    }

    /**
     * Marlin FP16×INT4 GEMM. Returns {@code null} when Marlin is not built.
     *
     * @param a      FP16 activations {@code [M,K]}.
     * @param b      Marlin-packed INT4 weights.
     * @param scales group scales.
     * @param workspace scratch buffer (may be empty).
     * @param threadK Marlin thread_k (-1 = auto).
     */
    public static Tensor marlinMul(Tensor a, Tensor b, Tensor scales, Tensor workspace, int threadK) {
        if (Bindings.MARLIN_MUL == null) {
            throw new IllegalStateException(
                    "smile_marlin_mul symbol not found (rebuild libsmile_torch with -DUSE_MARLIN=ON)");
        }
        MemorySegment out;
        try {
            // invokeExact requires an exact MemorySegment type; a ternary in the
            // argument list is typed as Object and fails the call-site check.
            MemorySegment wsHandle = workspace == null ? MemorySegment.NULL : workspace.handle();
            out = (MemorySegment) Bindings.MARLIN_MUL.invokeExact(
                    a.handle(), b.handle(), scales.handle(), wsHandle, threadK);
        } catch (Throwable t) {
            String err = lastError();
            throw new RuntimeException(
                    (err == null || err.isEmpty())
                            ? ("smile_marlin_mul native call failed: " + t.getMessage())
                            : err,
                    t);
        }
        if (out == null || out.address() == 0) {
            String err = lastError();
            throw new RuntimeException(
                    (err == null || err.isEmpty())
                            ? "smile_marlin_mul returned null without an error message"
                            : err);
        }
        return new Tensor(out);
    }

    /**
     * Sets {@code requires_grad} on every parameter of {@code module} (recursive).
     *
     * @param module        native {@code ST_Module} handle.
     * @param requiresGrad  {@code true} to enable autograd on parameters.
     */
    public static void moduleSetRequiresGrad(MemorySegment module, boolean requiresGrad) {
        try {
            Bindings.MODULE_SET_REQUIRES_GRAD.invokeExact(module, requiresGrad ? 1 : 0);
        } catch (Throwable t) {
            throw new RuntimeException(lastError().isEmpty() ? t.getMessage() : lastError(), t);
        }
        String err = lastError();
        if (!err.isEmpty()) {
            throw new RuntimeException(err);
        }
    }

    /**
     * Unregisters a child module by name, dropping the parent's shared_ptr.
     * Used when replacing dense {@code LinearLayer} shells with quantized ops
     * so GPU storage is released before KV pool sizing.
     *
     * @param module parent {@code ST_Module}.
     * @param name   registered child name (e.g. {@code "wq"}).
     */
    public static void unregisterModule(MemorySegment module, String name) {
        if (Bindings.MODULE_UNREGISTER == null) {
            throw new UnsupportedOperationException(
                    "smile_module_unregister_module missing; rebuild libsmile_torch");
        }
        try (Arena arena = Arena.ofConfined()) {
            Bindings.MODULE_UNREGISTER.invokeExact(module, arena.allocateFrom(name));
        } catch (Throwable t) {
            throw new RuntimeException(lastError().isEmpty() ? t.getMessage() : lastError(), t);
        }
        String err = lastError();
        if (!err.isEmpty()) {
            throw new RuntimeException(err);
        }
    }

    /**
     * Returns the storage size of {@code tensor} in bytes.
     *
     * @param tensor the tensor.
     * @return {@code tensor.nbytes()}.
     */
    public static long nbytes(Tensor tensor) {
        try {
            return (long) Bindings.TENSOR_NBYTES.invokeExact(tensor.handle());
        } catch (Throwable t) {
            throw new RuntimeException("smile_tensor_nbytes failed", t);
        }
    }

    /**
     * Returns a writable {@link MemorySegment} covering the contiguous storage
     * of {@code tensor} ({@code nbytes} bytes). The tensor must be contiguous
     * and remain reachable for the lifetime of the segment.
     *
     * @param tensor the contiguous tensor.
     * @return the storage segment.
     */
    public static MemorySegment dataPtr(Tensor tensor) {
        long nbytes = nbytes(tensor);
        MemorySegment ptr;
        try {
            ptr = (MemorySegment) Bindings.TENSOR_DATA_PTR.invokeExact(tensor.handle());
        } catch (Throwable t) {
            throw new RuntimeException("smile_tensor_data_ptr failed", t);
        }
        if (ptr == null || ptr.address() == 0) {
            if (nbytes == 0) {
                return MemorySegment.NULL;
            }
            throw new RuntimeException("smile_tensor_data_ptr returned null");
        }
        return ptr.reinterpret(nbytes);
    }

    /**
     * In-place sum all-reduce across tensors that already reside on distinct devices.
     *
     * @param tensors one tensor per TP rank (same shape/dtype).
     */
    public static void tpAllReduceSum(Tensor[] tensors) {
        if (tensors == null || tensors.length <= 1) {
            return;
        }
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment arr = arena.allocate(ValueLayout.ADDRESS, tensors.length);
            for (int i = 0; i < tensors.length; i++) {
                arr.setAtIndex(ValueLayout.ADDRESS, i, tensors[i].handle());
            }
            int rc;
            try {
                rc = (int) Bindings.TP_ALL_REDUCE_SUM.invokeExact(arr, tensors.length);
            } catch (Throwable t) {
                throw new RuntimeException("smile_tp_all_reduce_sum failed", t);
            }
            if (rc != 0) {
                String msg = lastError();
                throw new RuntimeException(msg.isEmpty() ? "smile_tp_all_reduce_sum failed" : msg);
            }
        }
    }

    /**
     * Broadcasts {@code tensors[root]} onto every other entry.
     */
    public static void tpBroadcast(Tensor[] tensors, int root) {
        if (tensors == null || tensors.length <= 1) {
            return;
        }
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment arr = arena.allocate(ValueLayout.ADDRESS, tensors.length);
            for (int i = 0; i < tensors.length; i++) {
                arr.setAtIndex(ValueLayout.ADDRESS, i, tensors[i].handle());
            }
            int rc;
            try {
                rc = (int) Bindings.TP_BROADCAST.invokeExact(arr, tensors.length, root);
            } catch (Throwable t) {
                throw new RuntimeException("smile_tp_broadcast failed", t);
            }
            if (rc != 0) {
                String msg = lastError();
                throw new RuntimeException(msg.isEmpty() ? "smile_tp_broadcast failed" : msg);
            }
        }
    }

    /**
     * Creates a local NCCL communicator for {@code deviceIndices}, or returns
     * {@link MemorySegment#NULL} when NCCL is unavailable.
     */
    public static MemorySegment ncclCommCreate(int[] deviceIndices) {
        if (deviceIndices == null || deviceIndices.length < 1) {
            return MemorySegment.NULL;
        }
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment devices = arena.allocate(ValueLayout.JAVA_INT, deviceIndices.length);
            for (int i = 0; i < deviceIndices.length; i++) {
                devices.setAtIndex(ValueLayout.JAVA_INT, i, deviceIndices[i]);
            }
            MemorySegment comm;
            try {
                comm = (MemorySegment) Bindings.NCCL_COMM_CREATE.invokeExact(
                        deviceIndices.length, devices);
            } catch (Throwable t) {
                return MemorySegment.NULL;
            }
            if (comm == null || comm.address() == 0) {
                return MemorySegment.NULL;
            }
            return comm;
        }
    }

    /** Destroys an NCCL communicator from {@link #ncclCommCreate}. */
    public static void ncclCommFree(MemorySegment comm) {
        if (comm == null || comm.address() == 0) {
            return;
        }
        try {
            Bindings.NCCL_COMM_FREE.invokeExact(comm);
        } catch (Throwable ignored) {
            // best-effort
        }
    }

    /**
     * In-place NCCL sum all-reduce on {@code local} for {@code rank}.
     * Every TP rank must call concurrently.
     */
    public static void ncclAllReduceSum(MemorySegment comm, int rank, Tensor local) {
        if (comm == null || comm.address() == 0) {
            throw new IllegalStateException("NCCL communicator is null");
        }
        int rc;
        try {
            rc = (int) Bindings.NCCL_ALL_REDUCE_SUM.invokeExact(comm, rank, local.handle());
        } catch (Throwable t) {
            throw new RuntimeException(lastError().isEmpty() ? t.getMessage() : lastError(), t);
        }
        if (rc != 0) {
            String msg = lastError();
            throw new RuntimeException(msg.isEmpty() ? "smile_nccl_all_reduce_sum failed" : msg);
        }
    }

    /**
     * NCCL broadcast of {@code local} from {@code root}. Every rank must call
     * concurrently with its buffer.
     */
    public static void ncclBroadcast(MemorySegment comm, int rank, int root, Tensor local) {
        if (comm == null || comm.address() == 0) {
            throw new IllegalStateException("NCCL communicator is null");
        }
        int rc;
        try {
            rc = (int) Bindings.NCCL_BROADCAST.invokeExact(comm, rank, root, local.handle());
        } catch (Throwable t) {
            throw new RuntimeException(lastError().isEmpty() ? t.getMessage() : lastError(), t);
        }
        if (rc != 0) {
            String msg = lastError();
            throw new RuntimeException(msg.isEmpty() ? "smile_nccl_broadcast failed" : msg);
        }
    }

    /**
     * Fused recurrent gated delta rule. Mutates float {@code state} in place.
     * Returns output {@code [B,S,H,Dv]} (caller owns).
     *
     * @return output tensor, or {@code null} if the native path is unavailable.
     */
    public static Tensor recurrentGatedDeltaRule(
            Tensor query, Tensor key, Tensor value,
            Tensor g, Tensor beta, Tensor state, boolean qkL2norm) {
        MemorySegment out;
        try {
            out = (MemorySegment) Bindings.RECURRENT_GATED_DELTA.invokeExact(
                    query.handle(), key.handle(), value.handle(),
                    g.handle(), beta.handle(), state.handle(),
                    qkL2norm ? 1 : 0);
        } catch (Throwable t) {
            String err = lastError();
            if (err != null && !err.isEmpty()) {
                throw new RuntimeException(err, t);
            }
            return null;
        }
        if (out == null || out.address() == 0) {
            String err = lastError();
            if (err != null && !err.isEmpty()) {
                throw new RuntimeException(err);
            }
            return null;
        }
        return new Tensor(out);
    }

    /**
     * Sets the FlashInfer AOT / jit-cache directory for the native loader.
     *
     * @param path absolute directory, or {@code null}/empty to clear.
     */
    public static void flashInferSetAotDir(String path) {
        if (Bindings.FLASHINFER_SET_AOT == null) {
            return;
        }
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment cstr = (path == null || path.isEmpty())
                    ? MemorySegment.NULL
                    : arena.allocateFrom(path);
            Bindings.FLASHINFER_SET_AOT.invokeExact(cstr);
        } catch (Throwable t) {
            throw new RuntimeException("smile_flashinfer_set_aot_dir failed", t);
        }
    }

    /**
     * @return {@code true} when FlashInfer paged attention is compiled into
     * {@code libsmile_torch}.
     */
    public static boolean flashInferAvailable() {
        if (Bindings.FLASHINFER_AVAILABLE == null) {
            return false;
        }
        try {
            return ((int) Bindings.FLASHINFER_AVAILABLE.invokeExact()) != 0;
        } catch (Throwable t) {
            return false;
        }
    }

    /**
     * Creates a FlashInfer workspace on {@code deviceIndex}.
     * @return native handle, or null when unavailable.
     */
    public static MemorySegment flashInferWorkspaceCreate(int deviceIndex, long workspaceBytes) {
        if (Bindings.FLASHINFER_WS_CREATE == null) {
            return null;
        }
        try {
            MemorySegment h = (MemorySegment) Bindings.FLASHINFER_WS_CREATE.invokeExact(
                    deviceIndex, workspaceBytes);
            if (h == null || h.address() == 0) {
                return null;
            }
            return h;
        } catch (Throwable t) {
            return null;
        }
    }

    /** Frees a FlashInfer workspace handle. */
    public static void flashInferWorkspaceFree(MemorySegment handle) {
        if (handle == null || handle.address() == 0 || Bindings.FLASHINFER_WS_FREE == null) {
            return;
        }
        try {
            Bindings.FLASHINFER_WS_FREE.invokeExact(handle);
        } catch (Throwable ignored) {
            // best-effort
        }
    }

    /**
     * Runs paged attention using {@link smile.llm.attention.AttentionContext}.
     *
     * @param query query {@code [B, Hq, S, D]}
     * @param mask  optional additive attention mask (same as torch_native); may be null
     * @param ctx   paged context with pool + CSR + workspace
     * @return output {@code [B, Hq, S, D]}
     */
    public static Tensor flashInferAttention(Tensor query, Tensor mask,
                                             smile.llm.attention.AttentionContext ctx) {
        if (Bindings.FLASHINFER_PAGED == null) {
            throw new IllegalStateException("smile_flashinfer_paged_attention not in libsmile_torch");
        }
        var meta = ctx.kvMetadata();
        var pool = ctx.kvPool();
        var ws = ctx.workspace();
        if (meta == null || pool == null || ws == null) {
            throw new IllegalArgumentException("FlashInfer context incomplete");
        }
        // Ragged decode passes per-row lengths in CSR; cacheLen is row 0 only.
        int cacheLenArg = ctx.isRagged() ? 0 : ctx.cacheLen();
        try (var layerIdx = smile.deep.tensor.Index.of(ctx.layerId());
             Tensor layerK = pool.keyCache().get(layerIdx);
             Tensor layerV = pool.valueCache().get(layerIdx)) {
            MemorySegment out;
            try {
                // invokeExact requires an exact MemorySegment type; a ternary in the
                // argument list is typed as Object and fails the call-site check.
                MemorySegment maskHandle = mask == null ? MemorySegment.NULL : mask.handle();
                out = (MemorySegment) Bindings.FLASHINFER_PAGED.invokeExact(
                        query.handle(),
                        layerK.handle(),
                        layerV.handle(),
                        meta.pagedKvIndptr().handle(),
                        meta.pagedKvIndices().handle(),
                        meta.pagedKvLastPageLen().handle(),
                        meta.pageSize(),
                        ctx.numKvHeads(),
                        ctx.headDim(),
                        cacheLenArg,
                        ctx.scale(),
                        pool.kScale(),
                        pool.vScale(),
                        ctx.isCausal() ? 1 : 0,
                        maskHandle,
                        ws.handle());
            } catch (Throwable t) {
                throw new RuntimeException(lastError().isEmpty() ? t.getMessage() : lastError(), t);
            }
            return new Tensor(check(out));
        }
    }

    /**
     * Runs ragged contiguous self-attention ({@code BatchPrefillWithRaggedKVCache} or SDPA fallback).
     *
     * @param query {@code [N, H, D]} NHD
     * @param key   {@code [N, H, D]}
     * @param value {@code [N, H, D]}
     * @param mask  optional additive mask; may be null
     * @param ctx   ragged context with {@link smile.llm.attention.AttentionContext#raggedIndptr()}
     * @return output {@code [N, H, D]}
     */
    public static Tensor flashInferRaggedAttention(Tensor query, Tensor key, Tensor value,
                                                   Tensor mask,
                                                   smile.llm.attention.AttentionContext ctx) {
        if (Bindings.FLASHINFER_RAGGED == null) {
            throw new IllegalStateException("smile_flashinfer_ragged_attention not in libsmile_torch");
        }
        int[] indptr = ctx.raggedIndptr();
        if (indptr == null || indptr.length < 2) {
            throw new IllegalArgumentException("FlashInfer ragged context requires indptr [B+1]");
        }
        try (Tensor indptrT = Tensor.of(indptr).to(query.device()).to(smile.deep.tensor.ScalarType.Int32)) {
            MemorySegment out;
            try {
                MemorySegment maskHandle = mask == null ? MemorySegment.NULL : mask.handle();
                out = (MemorySegment) Bindings.FLASHINFER_RAGGED.invokeExact(
                        query.handle(),
                        key.handle(),
                        value.handle(),
                        indptrT.handle(),
                        ctx.numKvHeads(),
                        ctx.headDim(),
                        ctx.scale(),
                        ctx.isCausal() ? 1 : 0,
                        maskHandle);
            } catch (Throwable t) {
                throw new RuntimeException(lastError().isEmpty() ? t.getMessage() : lastError(), t);
            }
            return new Tensor(check(out));
        }
    }

    /** Frees an {@code ST_Tensor} handle exactly once. Used as a cleaning action. */
    public record FreeTensor(MemorySegment handle) implements Runnable {
        @Override public void run() {
            smile_torch_h.smile_tensor_free(handle);
        }
    }

    /** Frees an {@code ST_TensorIndex} handle exactly once. Used as a cleaning action. */
    public record FreeIndex(MemorySegment handle) implements Runnable {
        @Override public void run() {
            smile_torch_h.smile_tensor_index_free(handle);
        }
    }
}
