/*
 * Copyright (c) 2010-2026 Haifeng Li. All rights reserved.
 *
 * SMILE is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SMILE is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SMILE. If not, see <https://www.gnu.org/licenses/>.
 */
package smile.llm;

import java.time.Instant;

/**
 * LLM conversation messages.
 * @param role the role of message speaker. Messages with the assistant role
 *             are presumed to have been generated by the model in previous
 *             interactions.
 * @param content the message content.
 * @param error the service message if any error occurred.
 * @param timestamp the message timestamp.
 *
 * @author Haifeng Li
 */
public record Message(Role role, String content, String error, Instant timestamp) {
    /**
     * Constructor of a user message.
     * @param content the message content.
     */
    public Message(String content) {
        this(Role.user, content, null, Instant.now());
    }

    /**
     * Constructor of an assistant message.
     * @param content the message content.
     * @param error the service message if any error occurred.
     */
    public Message(String content, String error) {
        this(Role.assistant, content, error, Instant.now());
    }
}
