/*
 * Copyright (c) 2010-2026 Haifeng Li. All rights reserved.
 *
 * SMILE Studio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SMILE Studio is distributed in the hope that it will be useful,
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SMILE. If not, see <https://www.gnu.org/licenses/>.
 */
package smile.llm;

import java.time.Instant;

/**
 * LLM conversation messages.
 * @param role the role of message speaker. Messages with the assistant role
 *             are presumed to have been generated by the model in previous
 *             interactions.
 * @param content the message content.
 * @param toolCall the tool call that this message is responding to.
 * @param timestamp the message timestamp.
 *
 * @author Haifeng Li
 */
public record Message(Role role, String content, ToolCall toolCall, Instant timestamp) {
    /**
     * Returns a system message.
     * @param content the message content.
     * @return a system message with the current timestamp.
     */
    public static Message system(String content) {
        return new Message(Role.system, content, null, Instant.now());
    }

    /**
     * Returns a user message.
     * @param content the message content.
     *  @return a user message with the current timestamp.
     */
    public static Message user(String content) {
        return new Message(Role.user, content, null, Instant.now());
    }

    /**
     * Returns an assistant message.
     * @param content the message content.
     *  @return an assistant message with the current timestamp.
     */
    public static Message assistant(String content) {
        return new Message(Role.assistant, content, null, Instant.now());
    }

    /**
     * Returns a tool call message.
     * @param id the id of tool call.
     * @param name the tool name.
     * @param input the input of tool call.
     * @param output the output of tool call.
     * @return a tool call message with the current timestamp.
     */
    public static Message toolCall(String id, String name, Object input, String output) {
        return new Message(Role.tool, null, new ToolCall(id, name, input, output), Instant.now());
    }

    /**
     * Returns an error message.
     * @param content the message content.
     * @return an error message with the current timestamp.
     */
    public static Message error(String content) {
        return new Message(Role.error, content, null, Instant.now());
    }
}
