/*
 * Copyright (c) 2010-2026 Haifeng Li. All rights reserved.
 *
 * SMILE is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SMILE is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SMILE. If not, see <https://www.gnu.org/licenses/>.
 */
package smile.neighbor;

import java.io.Serial;
import java.io.Serializable;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.BitSet;
import java.util.List;

import smile.math.MathEx;
import smile.math.distance.HammingDistance;
import smile.hash.SimHash;
import smile.util.IntArrayList;
import smile.util.LongArrayList;
import smile.util.LongObjectHashMap;

/**
 * Locality-Sensitive Hashing for Signatures.
 * LSH is an efficient algorithm for approximate nearest neighbor search
 * in high dimensional spaces by performing probabilistic dimension reduction
 * of data. The basic idea is to hash the input items so that similar items
 * are mapped to the same buckets with high probability (the number of buckets
 * being much smaller than the universe of possible input items).
 * If we are given signatures for the sets, we may divide them into bands,
 * and only measure the similarity of a pair of sets if they are identical
 * in at least one band. By choosing the size of bands appropriately, we can
 * eliminate most of the pairs that do not meet our threshold of similarity.
 * <p>
 * By default, the query object (reference equality) is excluded from the
 * neighborhood. Note that you may observe weird behavior with String objects.
 * JVM will pool the string literal objects. So the below variables
 * <code>
 *     String a = "ABC";
 *     String b = "ABC";
 *     String c = "AB" + "C";
 * </code>
 * are actually equal in reference test <code>a == b == c</code>. With toy data
 * that you type explicitly in the code, this will cause problems. Fortunately,
 * the data would be generally read from secondary storage in production.
 *
 * <h2>References</h2>
 * <ol>
 * <li>Moses S. Charikar. Similarity Estimation Techniques from Rounding Algorithms</li>
 * </ol>
 *
 * @see LSH
 * @see smile.hash.SimHash
 *
 * @param <K> the type of keys.
 * @param <V> the type of associated objects.
 *
 * @author Qiyang Zuo
 */
public class SNLSH<K, V> implements RNNSearch<K, V>, Serializable {
    @Serial
    private static final long serialVersionUID = 2L;

    /** Hash function mask. */
    private final long mask;
    /** The number of bits of hash function. */
    private static final int BITS = 64;
    /**
     * Signature fractions — one primitive long-keyed map per band.
     * Using {@link LongObjectHashMap} eliminates autoboxing of the
     * band-hash key that would otherwise be incurred by
     * {@code LinkedHashMap<Long, IntArrayList>}.
     */
    @SuppressWarnings("unchecked")
    private final LongObjectHashMap<IntArrayList>[] bands;
    /**
     * The data objects.
     */
    private final List<V> data = new ArrayList<>();
    /**
     * The keys of data objects.
     */
    private final List<K> keys = new ArrayList<>();
    /**
     * The signatures generated by simhash, stored as primitive longs to
     * avoid the boxing overhead of {@code List<Long>}.
     */
    private final LongArrayList signatures = new LongArrayList();
    /**
     * SimHash function.
     */
    private final SimHash<K> simhash;

    /**
     * Constructor.
     * @param L the number of bands/hash tables.
     * @param hash simhash function.
     */
    @SuppressWarnings("unchecked")
    public SNLSH(int L, SimHash<K> hash) {
        if (L < 2 || L > 32) {
            throw new IllegalArgumentException("Invalid band size!");
        }

        simhash = hash;
        bands = (LongObjectHashMap<IntArrayList>[]) Array.newInstance(LongObjectHashMap.class, L);
        for (int i = 0; i < L; i++) {
            bands[i] = new LongObjectHashMap<>();
        }
        mask = -1L >>> (BITS / L * (L - 1));
    }

    /**
     * Returns the number of data objects stored in this SNLSH.
     * @return the number of data objects.
     */
    public int size() {
        return data.size();
    }

    /**
     * Adds a new item.
     * @param key the key.
     * @param value the value.
     */
    public void put(K key, V value) {
        int index = data.size();
        keys.add(key);
        data.add(value);

        long signature = simhash.hash(key);
        signatures.add(signature);

        for (int i = 0; i < bands.length; i++) {
            long bandKey = bandHash(signature, i);
            IntArrayList bucket = bands[i].get(bandKey);
            if (bucket == null) {
                bucket = new IntArrayList();
                bands[i].put(bandKey, bucket);
            }
            // bucket is already in the map; just append the new index in place.
            bucket.add(index);
        }
    }

    @Override
    public void search(K q, double radius, List<Neighbor<K, V>> neighbors) {
        if (radius <= 0 || radius != (int) radius) {
            throw new IllegalArgumentException("The parameter radius has to be an integer: " + radius);
        }

        // Compute the query signature once and reuse it for both candidate
        // lookup and Hamming distance evaluation.
        long fpq = simhash.hash(q);
        IntArrayList candidates = getCandidates(fpq);
        int n = candidates.size();
        for (int ci = 0; ci < n; ci++) {
            int index = candidates.get(ci);
            int distance = HammingDistance.d(fpq, signatures.get(index));
            if (MathEx.le(distance, radius)) {
                neighbors.add(new Neighbor<>(keys.get(index), data.get(index), index, distance));
            }
        }
    }

    /**
     * Calculates the hash value for a band.
     */
    private long bandHash(long hash, int band) {
        return (hash >>> (band * (BITS / bands.length))) & mask;
    }

    /**
     * Returns the unique nearest neighbor candidate indices.
     * Uses a {@link BitSet} for O(1) no-boxing duplicate detection and an
     * {@link IntArrayList} for cache-friendly indexed iteration.
     * The query signature is passed in to avoid hashing the query twice.
     *
     * @param fpq the pre-computed SimHash signature of the query.
     * @return deduplicated candidate indices.
     */
    private IntArrayList getCandidates(long fpq) {
        BitSet seen = new BitSet(data.size());
        IntArrayList candidates = new IntArrayList();
        for (int i = 0; i < bands.length; i++) {
            long bandKey = bandHash(fpq, i);
            IntArrayList bucket = bands[i].get(bandKey);
            if (bucket != null) {
                int n = bucket.size();
                for (int j = 0; j < n; j++) {
                    int idx = bucket.get(j);
                    if (!seen.get(idx)) {
                        seen.set(idx);
                        candidates.add(idx);
                    }
                }
            }
        }
        return candidates;
    }
}
