###############################################################################
# Copyright (c) 2010-2026 Haifeng Li. All rights reserved.
#
# SMILE is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SMILE is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SMILE. If not, see <https://www.gnu.org/licenses/>.
###############################################################################

SaveTitle=Save Changes
SaveMessage=The notebook {0} is not saved. Save changes?
OpenNotebook=Open Notebook
SaveNotebook=Save Notebook
SmileFile=SMILE Notebook (*.java, *.jsh, *.scala, *.sc, *.py, *.ipynb)
ExternalChangeTitle=File Changed on Disk
ExternalChangeMessage=The file "{0}" has been modified by another program.\n\
  Do you want to reload it from disk? Unsaved changes will be lost.
AnalystWelcome======================================================================\n\
Welcome! I am Clair, your AI assistant for machine learning modeling.\n\
\n\
/help for available commands, /init for initializing your project\n\
cwd: {0}
AnalystTips=As a state-of-the-art machine learning engineering agent, I can help you with:\n\
\n\
🤖 Automatic end-to-end ML/AI solutions based on your requirements.\n\
🔍 Best practices and state-of-the-art methods with web search.\n\
🏅 Targeted code block refinement by ablation study.\n\
🤝 Improved solution using iterative ensemble strategy.\n\
📊 Advanced interactive data visualization.\n\
📂 Process data from CSV, ARFF, JSON, Avro, Parquet, Iceberg, to SQL.\n\
🌐 Built-in inference server.\n\
\n\
💡 Tips for getting started:\n\
1. Shift + ENTER to add a line break in your prompt.\n\
2. Run /init to create a SMILE.md file with instructions for agents.\n\
3. Be as specific as you would with another data scientist for the best result.\n\
4. Data visualization can be feed to AI agents for interpretation and advices.\n\
5. Create custom slash commands for reusable prompts or workflows.\n\
6. Run Shell commands starting with an exclamation mark (!).\n\
7. AI can make mistakes. Always review agent's responses.
JavaCoderWelcome======================================================================\n\
Welcome! I am James, your AI assistant for Java programming.\n\
\n\
I can help with code completion and generation in the notebook too.\n\
cwd: {0}
PythonCoderWelcome======================================================================\n\
Welcome! I am Guido, your AI assistant for Python programming.\n\
\n\
I can help with code completion and generation in the notebook too.\n\
cwd: {0}
CoderTips=💡 Tips for getting started:\n\
1. Shift + ENTER to add a line break in your prompt.\n\
2. TAB to complete code in the notebook.\n\
3. Be as specific as you would with another programmer for the best result.\n\
4. Create custom slash commands for reusable prompts or workflows.\n\
5. Run Shell commands starting with an exclamation mark (!).\n\
6. AI can make mistakes. Always review agent's responses.
