/*
 * Copyright (c) 2010-2026 Haifeng Li. All rights reserved.
 *
 * SMILE is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SMILE is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SMILE. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Type-safe enumerations and constants for BLAS, LAPACK, and ARPACK.
 *
 * <p>All classes in this package are thin, allocation-free wrappers around the
 * integer and byte flags consumed by the native libraries.  Using these enums
 * instead of raw integer literals makes call sites self-documenting and prevents
 * hard-to-detect argument-ordering bugs.
 *
 * <h2>Enum overview</h2>
 * <table>
 *   <caption>smile.linalg enumerations</caption>
 *   <tr><th>Enum</th><th>Purpose</th><th>Used by</th></tr>
 *   <tr><td>{@link smile.linalg.Order}</td>
 *       <td>Matrix memory layout: {@code ROW_MAJOR} (C) vs {@code COL_MAJOR} (Fortran)</td>
 *       <td>CBLAS, CLAPACK</td></tr>
 *   <tr><td>{@link smile.linalg.Transpose}</td>
 *       <td>Matrix operation: none / transpose / conjugate-transpose</td>
 *       <td>CBLAS, CLAPACK</td></tr>
 *   <tr><td>{@link smile.linalg.UPLO}</td>
 *       <td>Which triangle is stored for symmetric/triangular matrices</td>
 *       <td>CBLAS, CLAPACK</td></tr>
 *   <tr><td>{@link smile.linalg.Diag}</td>
 *       <td>Whether a triangular matrix has a unit diagonal</td>
 *       <td>CBLAS, CLAPACK</td></tr>
 *   <tr><td>{@link smile.linalg.Side}</td>
 *       <td>Whether a symmetric matrix multiplies on the left or right</td>
 *       <td>CBLAS</td></tr>
 *   <tr><td>{@link smile.linalg.EVDJob}</td>
 *       <td>Whether eigenvectors are computed ({@code dgeev}, {@code dsyevd})</td>
 *       <td>CLAPACK</td></tr>
 *   <tr><td>{@link smile.linalg.SVDJob}</td>
 *       <td>Which singular vectors are computed ({@code dgesdd})</td>
 *       <td>CLAPACK</td></tr>
 *   <tr><td>{@link smile.linalg.EigenRange}</td>
 *       <td>Range of eigenvalues to compute ({@code dsyevr})</td>
 *       <td>CLAPACK</td></tr>
 * </table>
 *
 * <h2>Native library bindings</h2>
 * <p>The sub-packages contain Java bindings generated by {@code jextract} (Java
 * Foreign Function &amp; Memory API, Java 22+):
 * <ul>
 *   <li>{@code smile.linalg.blas}   — CBLAS (OpenBLAS / Accelerate / MKL)</li>
 *   <li>{@code smile.linalg.lapack} — CLAPACK (OpenBLAS / Accelerate / MKL)</li>
 *   <li>{@code smile.linalg.arpack} — ARPACK (sparse eigendecomposition)</li>
 * </ul>
 * The native library name is controlled at runtime via system properties:
 * <ul>
 *   <li>{@code smile.lib.blas} — overrides the BLAS library name
 *       (default: {@code openblas} on Linux, {@code blas} on macOS, {@code libopenblas} on Windows).</li>
 * </ul>
 *
 * @author Haifeng Li
 */
package smile.linalg;
