// Generated by jextract

package smile.linalg.lapack;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     __CLPK_doublereal r;
 *     __CLPK_doublereal i;
 * }
 * }
 */
public class __CLPK_doublecomplex {

    __CLPK_doublecomplex() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        clapack_h.C_DOUBLE.withName("r"),
        clapack_h.C_DOUBLE.withName("i")
    ).withName("$anon$60:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble r$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("r"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __CLPK_doublereal r
     * }
     */
    public static final OfDouble r$layout() {
        return r$LAYOUT;
    }

    private static final long r$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __CLPK_doublereal r
     * }
     */
    public static final long r$offset() {
        return r$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __CLPK_doublereal r
     * }
     */
    public static double r(MemorySegment struct) {
        return struct.get(r$LAYOUT, r$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __CLPK_doublereal r
     * }
     */
    public static void r(MemorySegment struct, double fieldValue) {
        struct.set(r$LAYOUT, r$OFFSET, fieldValue);
    }

    private static final OfDouble i$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("i"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __CLPK_doublereal i
     * }
     */
    public static final OfDouble i$layout() {
        return i$LAYOUT;
    }

    private static final long i$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __CLPK_doublereal i
     * }
     */
    public static final long i$offset() {
        return i$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __CLPK_doublereal i
     * }
     */
    public static double i(MemorySegment struct) {
        return struct.get(i$LAYOUT, i$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __CLPK_doublereal i
     * }
     */
    public static void i(MemorySegment struct, double fieldValue) {
        struct.set(i$LAYOUT, i$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

