// Generated by jextract

package smile.onnx.foreign;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OrtNodeFusionOptions {
 *     uint32_t ort_version_supported;
 *     bool drop_constant_initializers;
 * }
 * }
 */
public class OrtNodeFusionOptions {

    OrtNodeFusionOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        onnxruntime_c_api_h.C_INT.withName("ort_version_supported"),
        onnxruntime_c_api_h.C_BOOL.withName("drop_constant_initializers"),
        MemoryLayout.paddingLayout(3)
    ).withName("OrtNodeFusionOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt ort_version_supported$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ort_version_supported"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static final OfInt ort_version_supported$layout() {
        return ort_version_supported$LAYOUT;
    }

    private static final long ort_version_supported$OFFSET = $LAYOUT.byteOffset(groupElement("ort_version_supported"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static final long ort_version_supported$offset() {
        return ort_version_supported$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static int ort_version_supported(MemorySegment struct) {
        return struct.get(ort_version_supported$LAYOUT, ort_version_supported$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static void ort_version_supported(MemorySegment struct, int fieldValue) {
        struct.set(ort_version_supported$LAYOUT, ort_version_supported$OFFSET, fieldValue);
    }

    private static final OfBoolean drop_constant_initializers$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("drop_constant_initializers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool drop_constant_initializers
     * }
     */
    public static final OfBoolean drop_constant_initializers$layout() {
        return drop_constant_initializers$LAYOUT;
    }

    private static final long drop_constant_initializers$OFFSET = $LAYOUT.byteOffset(groupElement("drop_constant_initializers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool drop_constant_initializers
     * }
     */
    public static final long drop_constant_initializers$offset() {
        return drop_constant_initializers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool drop_constant_initializers
     * }
     */
    public static boolean drop_constant_initializers(MemorySegment struct) {
        return struct.get(drop_constant_initializers$LAYOUT, drop_constant_initializers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool drop_constant_initializers
     * }
     */
    public static void drop_constant_initializers(MemorySegment struct, boolean fieldValue) {
        struct.set(drop_constant_initializers$LAYOUT, drop_constant_initializers$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

